version: '3'
services:

  #PHP FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www #mount binds: this project to /var/www/<project name>
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini #mount binds: local.ini file
    networks:
      - lara-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./:/var/www #mount binds: this project to /var/www/<project name>
      - ./nginx/conf.d/:/etc/nginx/conf.d/ #mount binds: this nginx/conf.d folder to /etc/nginx/conf.d/conf.d
    networks:
      - lara-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3303:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf #mount binds: from <project>/mysql/my.cnf to /etc/mysql/my.cnf in side container
    networks:
      - lara-network

#Docker Networks
networks:
  lara-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local